title: Changhun Lee's Profile and CV
domain: chlee-leo.github.io
url: https://chlee-leo.github.io
source:      .
destination: ./_site
includes:    ./_includes
baseurl: 
timezone: Asia/Seoul

collections:
  projects:
    output: true